name: ark
favicon: null
layout_spectrum: 0.5590406986884773
typography_spectrum: 0.2848501871339977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9607381438836455
  lightness: 0.3868172613438219
  saturation: 0.4525428630877286
  rhythmicContrast: 0.18685489892959595
purpose: []
